const express = require('express');
const router = express.Router();
const { list, create, get, update, remove } = require('../controllers/partController');
const authMiddleware = require('../middlewares/authMiddleware');
router.get('/', authMiddleware, list);
router.post('/', authMiddleware, create);
router.get('/:id', authMiddleware, get);
router.put('/:id', authMiddleware, update);
router.delete('/:id', authMiddleware, remove);
module.exports = router;
